# Generated by Django 5.0 on 2023-12-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
